/*
 * Copyright 2022 Sensative AB
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
import React from 'react';
import ReactRouter from 'storybook-react-router';

import {Link as LinkComponent} from './index';

// NOTE: Proptypes doesent seem to work so there are no autogenerated controls

const main = {
  title: 'Components/Yggio Links',
  component: LinkComponent,
  decorators: [ReactRouter()],
  parameters: {
    backgrounds: {
      default: 'dark',
    },
  },
};

const Template = args => <LinkComponent {...args} />;

const Link = Template.bind({});
Link.args = {
  url: '/destination',
  name: 'My link'
};

const Button = Template.bind({});
Button.args = {
  onClick: () => null,
  name: 'A link button'
};

export default main;
export {
  Link,
  Button,
};
