/*
 * Copyright 2022 Sensative AB
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
import React from 'react';
import ReactRouter from 'storybook-react-router';

import Navbar from './index';
import t from '../../utils/translation-prop';
import {YggioFontDecorator} from '../../decorators';

// NOTE: Proptypes doesent seem to work so there are no autogenerated controls

const main = {
  title: 'Yggio/Navbar',
  component: Navbar,
  decorators: [YggioFontDecorator, ReactRouter()],
  parameters: {
    layout: 'fullscreen',
  }
};

const Template = args => (
  <Navbar
    {...args}
    t={t}
    changeLanguage={() => null}
    signOut={() => null}
  />
);

const Primary = Template.bind({});
Primary.args = {
  currentLanguage: 'en',
  links: [
    {name: 'Devices', url: '/devices'},
    {name: 'Locations', url: '/locations'},
    {name: 'Organizations', url: '/organizations'},
  ],
  activeLink: '/devices',
};

export default main;
export {
  Primary,
};
